- name: add filebot apt-key
  apt_key:
    url: https://get.filebot.net/filebot/KEYS
    state: present

- name: add filebot apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://get.filebot.net/deb/ stable main'
    state: present
    filename: filebot
    update_cache: yes

- name: install filebot
  apt:
    name: filebot
    state: present
    update_cache: yes
