
- name: Stop and remove any existing container
  docker_container:
    name: unifi
    state: absent

- name: Create unifi directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/unifi

- name: Create and start container
  docker_container:
    name: unifi
    image: linuxserver/unifi-controller
    pull: yes
    published_ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/unifi:/config"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - unifi
    purge_networks: yes
    restart_policy: always
    state: started
